#!/bin/bash

cat > to-uppercase.sh << EOF
#!/bin/bash

# generated by 'gen-script.sh':

$(
  # find all not dirs
  find test -maxdepth 1 -type f -print0 |

  # files name separeted by '\0'
  while IFS= read -r -d $'\0' file; do

    # filename="${file#./}"
    file_name=$(basename -- "$file")
    dir_name=$(dirname -- "$file")
    
    # if not empty
    if [[ -n "$file_name" ]]; then

      uppercase_filename=$(echo "$file_name" | tr '[:lower:]' '[:upper:]')
      new_path="$dir_name/$uppercase_filename"

      # if changed
      if [[ "$file" != "$new_path" ]]; then
        echo "mv \"$file\" \"$new_path\""
      fi

    fi
  done
)
EOF

chmod +x to-uppercase.sh

echo "gen-script.sh: 'to-uppercase.sh' created"
